-- init.lua for VS Code Neovim
if not vim.g.vscode then
	return
end

vim.notify = require("vscode").notify
vim.opt.shortmess:append("asSScCAIWF")
vim.opt.showmode = false
vim.opt.report = 9999
vim.opt.laststatus = 0
vim.opt.showmode = false
vim.opt.cmdheight = 0
vim.opt.ruler = false
vim.opt.timeoutlen = 400
vim.opt.cmdheight = 0
vim.keymap.set({ "n", "v" }, "<Space>", "<Nop>", { silent = true })

local function map(mode, lhs, rhs, opts)
	vim.keymap.set(mode, lhs, rhs, opts or { silent = true })
end
map("n", "<Leader>q", function()
	require("vscode").action("workbench.action.closeWindow")
end)
map("n", "<Leader>w", function()
	require("vscode").action("workbench.action.files.save")
end)
map("n", "<Leader>n", function()
	require("vscode").action("welcome.showNewFileEntries")
end)

map("n", "|", function()
	require("vscode").action("workbench.action.splitEditor")
end)
map("n", "\\", function()
	require("vscode").action("workbench.action.splitEditorDown")
end)
map("n", "<C-H>", function()
	require("vscode").action("workbench.action.navigateLeft")
end)
map("n", "<C-J>", function()
	require("vscode").action("workbench.action.navigateDown")
end)
map("n", "<C-K>", function()
	require("vscode").action("workbench.action.navigateUp")
end)
map("n", "<C-L>", function()
	require("vscode").action("workbench.action.navigateRight")
end)

map("n", "<F7>", function()
	require("vscode").action("workbench.action.terminal.toggleTerminal")
end)
map("n", "<C-'>", function()
	require("vscode").action("workbench.action.terminal.toggleTerminal")
end)

map("n", "]b", "<Cmd>Tabnext<CR>")
map("n", "[b", "<Cmd>Tabprevious<CR>")
map("n", "<Leader>c", "<Cmd>Tabclose<CR>")
map("n", "<Leader>C", "<Cmd>Tabclose!<CR>")
map("n", "<Leader>bc", function()
	require("vscode").action("workbench.action.closeOtherEditors")
end)
map("n", "<Leader>bp", "<Cmd>Tablast<CR>")

map("n", "<Leader>e", function()
	require("vscode").action("workbench.files.action.focusFilesExplorer")
end)
map("n", "<Leader>o", function()
	require("vscode").action("workbench.files.action.focusFilesExplorer")
end)

map("v", "<Tab>", function()
	require("vscode").action("editor.action.indentLines")
end)
map("v", "<S-Tab>", function()
	require("vscode").action("editor.action.outdentLines")
end)

map("n", "]d", function()
	require("vscode").action("editor.action.marker.nextInFiles")
end)
map("n", "[d", function()
	require("vscode").action("editor.action.marker.prevInFiles")
end)

map("n", "<Leader>fc", function()
	require("vscode").action("workbench.action.findInFiles", { args = { query = vim.fn.expand("<cword>") } })
end)
map("n", "<Leader>fC", function()
	require("vscode").action("workbench.action.showCommands")
end)
map("n", "<Leader>ff", function()
	require("vscode").action("workbench.action.quickOpen")
end)
map("n", "<Leader>fn", function()
	require("vscode").action("notifications.showList")
end)
map("n", "<Leader>fo", function()
	require("vscode").action("workbench.action.openRecent")
end)
map("n", "<Leader>ft", function()
	require("vscode").action("workbench.action.selectTheme")
end)
map("n", "<Leader>fw", function()
	require("vscode").action("workbench.action.findInFiles")
end)
map("n", "<Leader>fb", function()
	require("vscode").action("workbench.action.showEditorsInGroup")
end)

map("n", "<Leader>gg", function()
	require("vscode").action("workbench.view.scm")
end)

map("n", "K", function()
	require("vscode").action("editor.action.showHover")
end)
map("n", "gI", function()
	require("vscode").action("editor.action.goToImplementation")
end)
map("n", "gd", function()
	require("vscode").action("editor.action.revealDefinition")
end)
map("n", "gD", function()
	require("vscode").action("editor.action.revealDeclaration")
end)
map("n", "gr", function()
	require("vscode").action("editor.action.goToReferences")
end)
map("n", "gy", function()
	require("vscode").action("editor.action.goToTypeDefinition")
end)
map("n", "<Leader>la", function()
	require("vscode").action("editor.action.quickFix")
end)
map("n", "<Leader>lG", function()
	require("vscode").action("workbench.action.showAllSymbols")
end)
map("n", "<Leader>lR", function()
	require("vscode").action("editor.action.goToReferences")
end)
map("n", "<Leader>lr", function()
	require("vscode").action("editor.action.rename")
end)
map("n", "<Leader>ls", function()
	require("vscode").action("workbench.action.gotoSymbol")
end)
map("n", "<Leader>lf", function()
	require("vscode").action("editor.action.formatDocument")
end)
